### ISSUE TITLE
IQueryableObjectSource not found exception

### ISSUE THREAD

**Issue by otryshko** [Giorgi/EFCore.Visualizer#30] opened 2024-03-13 15:39 UTC
![image](https://github.com/Giorgi/EFCore.Visualizer/assets/1059238/4e2653b1-d232-415c-aae8-2c31caaf5597)

**Comment by ErikEJ** [comment] 2024-03-13 15:44
Do you have VS 17.9?

**Comment by Giorgi** [comment] 2024-03-13 16:15
The IQueryableObjectSource.dll is included in the VSIX and should be available in the following folder: 

**C:\Users\G.Dalakishvili.SPLP0396\AppData\Local\Microsoft\VisualStudio\17.0_bd525d51\Extensions\qbklwbor.j3t\netcoreapp**

Can you check if it's there?

**Comment by otryshko** [comment] 2024-03-13 17:57
Yes, 17.9.1.

Yes, the file is in the folder which is on screenshot so I'm not sure what is going on. When I look at the dll with dotPeek, it seems that one reference does not work, but it could be a false positive


![image](https://github.com/Giorgi/EFCore.Visualizer/assets/1059238/87ad3814-6551-4721-b2da-fcd0007864d6)

**Comment by Giorgi** [comment] 2024-03-13 18:09
Can you run Procmon and see if the DLL is accessed or not?

**Comment by Giorgi** [comment] 2024-03-13 18:52
This is what I get when I run the visualizer:

![image](https://github.com/Giorgi/EFCore.Visualizer/assets/580749/72425da2-eef7-47a0-aa60-90a1b9b4f49e)

**Comment by otryshko** [comment] 2024-03-15 14:00
No, procmon doesn't capture any attempts to load IQueryableObjectSource

**Comment by Giorgi** [comment] 2024-03-15 16:07
@otryshko I have no idea why VS doesn't load the `IQueryableObjectSource.dll` but the error message you see is the same as the one in #28.

Can you post your steps to reproduce at https://developercommunity.visualstudio.com/t/SystemMissingMethodException-thrown-whe/10612094 ?

**Comment by ErikEJ** [comment] 2024-03-15 16:44
Can you share a repro project?

**Comment by otryshko** [comment] 2024-03-15 19:44
Figured it out; @Giorgi you were correct that it's related to the access denied to the extension folder (dll/Resources). The project is the asp.net core app running under the IIS AppPool identity. Once I granted the identity account access to the folder, it started to work.

Not sure if it's possible to check for it in advance/show better error message.

**Comment by Giorgi** [comment] 2024-03-15 20:09
Nice to hear that it's working now! I'm also not sure if it's possible to detect that but as the issue is now solved for you I'll close this issue.

**Closed by Giorgi** 2024-03-15 20:09 UTC
